### Cadastro de user
POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "Lua",
  "email": "lua@gmail.com",
  "password": "234567"
}

###
POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "Diego",
  "email": "lua@acme.com",
  "password": "123456"
}

### teste com a rota authenticate-with-password
POST http://localhost:3333/sessions/password
Content-Type: application/json

{
  "name": "Diego",
  "email": "lua@acme.com",
  "password": "123456"
}


### teste com a rota authenticate-with-password senha errada
POST http://localhost:3333/sessions/password
Content-Type: application/json

{
  "name": "Diego",
  "email": "lua@acme.com",
  "password": "123457"
}

### teste com erro de validacao do serivor 500
POST http://localhost:3333/sessions/password
Content-Type: application/json

{
  "name": "Diego",
  "email": "lua@acme.com",

}


### Obter Todos os Usuários
GET http://localhost:3333/users
Content-Type: application/json


### GET para a rota Profile - consulta user com ID
GET http://localhost:3333/profile
Authorization: Bearer RSNc
Content-Type: application/json


###teste com login de usuario no github

POST https://github.com/login/oauth/authorize?client_id=Ov23lieuyn2jx2qwPNNa&redirect_uri=http://localhost:3000/api/auth/callback&scope=user:email
Accept: application/json
{
  "access_token":"a",
  "scope":"repo,gist",
  "token_type":"bearer"
}