### Cadastro de user
POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "Lua",
  "email": "lua@gmail.com",
  "password": "234567"
}

###
POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "Diego",
  "email": "lua@acme.com",
  "password": "123456"
}

### teste com a rota authenticate-with-password
POST http://localhost:3333/sessions/password
Content-Type: application/json

{
  "name": "Diego",
  "email": "lua@acme.com",
  "password": "123456"
}


### teste com a rota authenticate-with-password senha errada
POST http://localhost:3333/sessions/password
Content-Type: application/json

{
  "name": "Diego",
  "email": "lua@acme.com",
  "password": "123457"
}

### teste com erro de validacao do serivor 500
POST http://localhost:3333/sessions/password
Content-Type: application/json

{
  "name": "Diego",
  "email": "lua@acme.com",

}


### Obter Todos os Usuários
GET http://localhost:3333/users
Content-Type: application/json


### GET para a rota Profile - consulta user com ID
GET http://localhost:3333/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMzllNmFiNS02OWQ4LTRlMzQtOWY5Ny00YzM3NzdjYjE2MGYiLCJpYXQiOjE3MTYzMzc2MzEsImV4cCI6MTcxNzIwMTYzMX0.wOTqRj_OVooew-vX-_C-gsT0gjmHKpPejy9IMlWED4U
Content-Type: application/json
